# Generated by Django 4.0.5 on 2022-07-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_remove_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(default='', upload_to='items/image'),
        ),
        migrations.AlterField(
            model_name='items',
            name='rprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='items',
            name='wprice',
            field=models.IntegerField(default=0),
        ),
    ]
